### ISSUE TITLE
iclod.com --> icloud.com

### ISSUE THREAD

**Issue by kirley** [charliepark/fat_fingers#11]
Hey guys,  I cam across a new typo that wasn't caught by fatfinger.  I fixed it like so, not sure if you're interested in including it in your gem?
```
    gsub(/@icl{0,2}oud\./,"@icloud.").
```

to 
```
    gsub(/@icl{0,2}o?u?d\./,"@icloud.").
```

**Comment by benrugg** [comment]
Hey @kirley - yeah, we'll include that! Can you submit a pull request with that change? (And also add it to the tests)
